SDK_VERSION="jucr-sdk.2024.12"
SDKIMAGE_FEATURES += "package-management"

# TCLIBC = "libc"
# FULL_OPTIMIZATION="-Os -pipe ${DEBUG_FLAGS}"
# SDK_NAME = "${DISTRO}-${TCLIBC}-${SDKMACHINE}-${IMAGE_BASENAME}-${TUNE_PKGARCH}-${MACHINE}"
# SDKPATHINSTALL = "/opt/${DISTRO}/${SDK_VERSION}"

# SDK_VENDOR = "-jucrsdk"
# SDK_VERSION = "${@d.getVar('DISTRO_VERSION').replace('snapshot-${METADATA_REVISION}', 'snapshot')}"
# SDK_VERSION[vardepvalue] = "${SDK_VERSION}"


